name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # to download fonts
          lfs: true
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
          echo $DOT_ENV > .env.local
          # show file size of .env.local
          ls -lsah | grep .env.local
          pnpm build
        env:
          DOT_ENV: ${{ vars.DOT_ENV }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy
        run: |
          zip -r build.zip build
          scp build.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:bergere-enchantee/build.zip
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "hostnamectl && cd bergere-enchantee && git fetch && git checkout $GITHUB_SHA && pnpm install && unzip -o build.zip && pm2 reload bergere"
